### ISSUE TITLE
Hay varias páinas de símbolos

### ISSUE THREAD

**Issue by psicobyte** [oslugr/carreras-en-cifras#6]
simbolos.csv, simbolosManu.csv, simbolos_UGR.csv.

Sospecho que es la última, pero tampoco está completa ¿no?

@Makova ,@molocohb

**Comment by Makova** [comment]
La de simbolosManu es la que hice yo hasta la mitad, más o menos. Habría que juntar la otra mitad de Mónica y ya estará.

**Comment by psicobyte** [comment]
El formato del archivo (nombres, mayúsculas, codificación, etc) debe ser exactamente el mismo que el del archivo "201415matriculasgradoramas.csv" que sacó @molocohb , porque si nó el programa no puede saber que es la misma carrera

**Comment by molocohb** [comment]
Veamos, la tabla definitiva sería la que se llama "matrículas normalizada", una copia de la que colgó Pablo en la sección "listas" pero donde estoy poniendo la lista de códigos. El asunto ahora es volcar los datos del resto de tablas en esta. Yo he hecho ya más o menos la mitad. 
Pablo, si lo estamos haciendo mal... dilo.

**Comment by psicobyte** [comment]
El únco requisito es que los nombres de las asignaturas coincidan con los que aparecen en 201415matriculasgradoramas.csv

Lo demás da lo mismo. pero, si los nombres no coinciden, el programa no sabe que son la misma asignatura y pone una "X" en lugar del icono que sea

**Comment by psicobyte** [comment]
Si queréis, itnetto pasar de una lista a otra de forma -más o menos- automanual, pero actualizad primero lo que tengáis, en un sólo fichero, para que no tengáis que duplicar trabajo

**Comment by Makova** [comment]
Por mi perfecto.

**Comment by Makova** [comment]
Habría que fusiona la de matriculas normalizadas con la de Manu.

**Comment by psicobyte** [comment]
Ok. Cuando lo tengáis me lo decís

**Comment by molocohb** [comment]
Lista de símbolos acabada y completa. He organizado un poco la carpeta para no volvernos locos, en la carpeta "Materiales" están las listas con las que hemos estado trabajando, la definitiva es "UGR completa"

**Comment by psicobyte** [comment]
Ok. Voy a ver qué puedo hacer.

**Comment by Makova** [comment]
Genial.

**Comment by psicobyte** [comment]
Resuelto
