### ISSUE TITLE
formatos

### ISSUE THREAD

**Issue by psicobyte** [oslugr/carreras-en-cifras#8]
Tened cuidado al abrir los archivos con distintos programas sicesivamente (como el calc, gedit, etc) porque se fastidia la codificación y los acentos y otros caracteres se pierden.

En particular, "simbolos_UGR.csv" está fastidiado más allá de toda salvación. Para arreglarlo hay que hacerlo a mano, acento por acento. @Makova @molocohb 

Si queréis, me pongo con ello, pero guardad y pushead antes todos los cambios, para que no se pierda el trabajo que habís hecho hasta ahora.

Si estáis de acuerdo, avisadme cuando lo hayáis hecho, corrijo los acentos y eso, y lo actualizo.

**Comment by Makova** [comment]
Done.

**Comment by psicobyte** [comment]
Resuelto
